name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Install Dependencies & Build
      #   run: yarn install

      # Runs a set of commands using the runners shell
      - name: Install Dependencies & Build
        run: |
          yarn install,
          yarn build,
          yarn lint